export enum EMensagem {
  AtualizadoSucesso = 'Atualizado com sucesso',
  DesativadoSucesso = 'Desativado com sucesso',
  DeveSerVazio = 'deve ser vazio',
  DeveSerInformado = 'deve ser informado',
  FilterInvalido = 'Filter inválido',
  IDsDiferentes = 'Os IDs informados são diferentes',
  ImpossivelAlterar = 'Impossível alterar o cadastro',
  ImpossivelCadastrar = 'Impossivel realizar o cadastro',
  ImpossivelDesativar = 'Impossivel desativar o cadastro',
  NaoPodeSerVazio = 'não pode ser vazio',
  NaoValido = 'não é válido',
  MaisCaracteresQuePermitido = 'possui mais caracteres que o permitido',
  OrderInvalido = 'Order inválido',
  SalvoSucesso = 'Salvo com sucesso',
}
