export enum EMensagem {
  AtualizadoSucesso = 'Atualizado com sucesso',
  AutenticadoSucesso = 'Autenticado com sucesso',
  DesativadoSucesso = 'Desativado com sucesso',
  DeveSerVazio = 'deve ser vazio',
  DeveSerInformado = 'deve ser informado',
  FilterInvalido = 'Filter inválido',
  IDsDiferentes = 'Os IDs informados são diferentes',
  ImpossivelAlterar = 'Impossível alterar',
  ImpossivelCadastrar = 'Impossivel realizar o cadastro',
  ImpossivelDesativar = 'Impossivel desativar o cadastro',
  NaoPodeSerVazio = 'não pode ser vazio',
  NaoValido = 'não é válido',
  MaisCaracteresQuePermitido = 'possui mais caracteres que o permitido',
  OrderInvalido = 'Order inválido',
  VerifiqueEnderecoEmailInformado = 'Verifique o endereço de e-mail informado',
  SalvoSucesso = 'Salvo com sucesso',
  TokenInvalido = 'Token Inválido',
  TipoInvalido = 'Tipo Inválido',
  UsuarioSenhaInvalido = 'Usuario e/ou senha inválidos',
  NaoFoiPossivelObterCredencial = 'Não foi possível obter a credencial',
}
